name: CI Básico Python

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        pip install -r app/requirements.txt

    - name: Ejecutar tests con cobertura
      run: |
        export PYTHONPATH=.
        pytest --cov=app --cov-report=term --cov-report=html app/tests/ -v

    - name: Guardar reporte
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/


    

