name: Deploy con Docker Compose

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Crear archivo .env
      run: |
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env

    - name: Parar servicios anteriores
      run: docker compose down -v || true

    - name: Construir servicios
      run: docker compose -f docker-compose.yml build

    - name: Levantar servicios
      run: docker compose -f docker-compose.yml up -d

    - name: Inicializar Base de Datos
      run: docker compose exec app flask init-db

    - name: Verificar app
      run: curl -f http://localhost/health