name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-on-local-runner:
    # Importante: Le dice a GitHub Actions que use tu runner local
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      # Construye la imagen y la etiqueta con el hash del commit para evitar colisiones
      run: docker build -t flask-app-test:${{ github.sha }} .

    - name: Run container
      # Inicia el contenedor en segundo plano
      run: docker run -d --name flask-test-container -p 5000:5000 flask-app-test:${{ github.sha }}

    - name: Wait for app to start
      run: sleep 10

    - name: Test service endpoints
      run: |
        echo "Testing / endpoint..."
        curl -f http://localhost:5000/
        echo "Testing /health endpoint..."
        curl -f http://localhost:5000/health

    - name: Run pytest inside container
      # Ejecuta los tests que están dentro del contenedor
      run: docker exec flask-test-container pytest

    - name: Cleanup container
      # Este paso se ejecuta siempre, incluso si los pasos anteriores fallan
      if: always()
      run: |
        docker stop flask-test-container
        docker rm flask-test-container
